=== vnvlabs/vnv/injection/json/vv_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://rnet-tech.net/vv.schema.json",
  "title": "Basic VV RunTime Schema",
  "description": "Schema for a VnV runtime Configuration file",
  "type": "object",
  "properties": {
    "testLibraries": {
      "$ref": "#/definitions/testLibraries"
    },
    "outputEngine": {
      "$ref": "#/definitions/outputEngine"
    },
    "runScopes": {
      "$ref": "#/definitions/runScopes"
    },
    "injectionPoints": {
      "$ref": "#/definitions/injectionPoints"
    }
  },
  "required": [
    "testLibraries",
    "outputEngine",
    "runScopes",
    "injectionPoints"
  ],
  "additionalProperties": false,
  "definitions": {
    "testLibraries": {
      "description": "Array containing the paths to  the plugin libraries to be imported",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^(.*).so$"
      },
      "uniqueItems": true
    },
    "outputEngine": {
      "description": "Parameters to configure the output Engine",
      "type": "object",
      "properties": {
        "outputFile": {
          "type": "string"
        },
        "debug": {
          "type": "boolean",
          "default": "false"
        },
        "configFile": {
          "type": "string",
          "description": "Path to the configuration File for the engine"
        },
        "type": {
          "type": "string",
          "description": "Registered Typename for the engine"
        },
        "extra": {
          "type": "object",
          "description": "Additional Configuration Properties to be sent to the Engine"
        }
      },
      "required": [
        "outputFile",
        "debug",
        "configFile",
        "type"
      ],
      "additionalProperties": false
    },
    "runScopes": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "description": " A single run Scope",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "run": {
            "type": "boolean",
            "default": true
          }
        },
        "required": [
          "name",
          "run"
        ]
      }
    },
    "injectionPoints": {
      "description": "Injection Points",
      "type": "array",
      "items": {
        "$ref": "#/definitions/injectionPoint"
      }
    },
    "injectionPoint": {
      "description": "An injection Point defined somewhere in the code",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "tests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/test"
          }
        }
      },
      "required": [
        "name"
      ]
    },
    "test": {
      "description": "Test information",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "stages": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/testStage"
          },
          "propertyNames": {
            "pattern": "^[0-9]*$"
          }
        },
        "testConfig": {
          "type": "object"
        },
        "runScope": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minLength": 1
        }
      },
      "required": [
        "name",
        "stages",
        "runScope"
      ],
      "additionalProperties": false
    },
    "testStage": {
      "type": "object",
      "properties": {
        "ipId": {
          "type": "integer"
        },
        "mapping": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "ipParameter": {
                "type": "string"
              },
              "transform": {
                "type": "string"
              }
            },
            "required": [
              "ipParameter"
            ]
          }
        }
      },
      "required": [
        "ipId",
        "mapping"
      ]
    }
  }
}

=== vnvlabs/vnv/injection/json/example.json
{
  "runScopes": [
    {
      "name": "debug",
      "run": true
    },
    {
      "name": "VnV",
      "run": false
    },
    {
      "name": "performance",
      "run": false
    }
  ],
  "testLibraries": [
    "hello/there/libTest.so",
    "hello/there/libTest1.so"
  ],
  "outputEngine": {
    "outputFile": "hello",
    "debug": true,
    "configFile": "there",
    "type": "debug",
    "extra": {
      "hello": "there",
      "another": "one",
      "not": "required"
    }
  },
  "injectionPoints": [
    {
      "name": "injectionPoint1",
      "tests": [
        {
          "name": "EuclideanError",
          "stages": {
            "0": {
              "ipId": 0,
              "mapping": {
                "test1": {
                  "ipParameter": "x"
                },
                "test2": {
                  "ipParameter": "y",
                  "transform": "y2z"
                }
              }
            },
            "1": {
              "ipId": -1,
              "mapping": {
                "test3": {
                  "ipParameter": "x"
                },
                "test4": {
                  "ipParameter": "x"
                }
              }
            }
          },
          "runScope": [
            "performance"
          ]
        }
      ]
    }
  ]
}
